name: Strategy Backtests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'

jobs:
  backtest-m7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run M7 Backtest
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: python scripts/backtest_m7.py
      
      - uses: actions/upload-artifact@v3
        with:
          name: m7-results
          path: results/m7_backtest_*.json

  backtest-w7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run W7 Backtest
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: python scripts/backtest_w7.py
      
      - uses: actions/upload-artifact@v3
        with:
          name: w7-results
          path: results/w7_backtest_*.json

  backtest-alphapulse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run AlphaPulse Backtest
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: python scripts/backtest_alphapulse.py
      
      - uses: actions/upload-artifact@v3
        with:
          name: alphapulse-results
          path: results/alphapulse_backtest_*.json
