name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: CI / lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PYTHONPATH: ${{ github.workspace }}
      LINT_EXCLUDE: |
        \.git|\.venv|venv|build|dist|__pycache__|
        trading/jobs/calibrate.py
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            pyproject.toml
            setup.cfg
            tox.ini

      - name: Install linters
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install "black~=24.0" "flake8~=7.0"

      # ВАЖНО: форматируем, а не --check, чтобы job не падал
      - name: Black (format)
        shell: bash
        run: |
          python -m black . --exclude "${LINT_EXCLUDE}"
          # показ диффа для информации, но не влияет на код возврата
          python -m black . --exclude "${LINT_EXCLUDE}" --diff --color

      # flake8 даёт предупреждения, но не роняет билд (на первом этапе миграции)
      - name: Flake8 (warnings only)
        shell: bash
        run: |
          flake8 . \
            --exclude "${LINT_EXCLUDE}" \
            --max-line-length 100 \
            --ignore E203,W503 \
            --exit-zero

  test:
    name: CI / test
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 30
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            pyproject.toml
            setup.cfg
            tox.ini
      - name: Install
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install "pytest~=8.0"
      - name: Pytest
        shell: bash
        run: |
          if [ -d tests ] || ls -1 **/*_test.py **/test_*.py 2>/dev/null | head -n1 >/dev/null; then
            pytest -q
          else
            echo "No tests found, skipping"
          fi

  typecheck:
    name: CI / typecheck
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 15
    env:
      PYTHONPATH: ${{ github.workspace }}
      MYPYPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            pyproject.toml
            mypy.ini
      - name: Install
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install "mypy~=1.10"
      - name: Bootstrap mypy.ini if missing
        shell: bash
        run: |
          if [ ! -f mypy.ini ] && [ ! -f pyproject.toml ]; then
            printf "%s\n" \
              "[mypy]" \
              "python_version = 3.11" \
              "warn_unused_ignores = True" \
              "warn_return_any = True" \
              "no_implicit_optional = True" \
              > mypy.ini
          fi
      - name: mypy
        shell: bash
        run: mypy .
