name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"           # встрой. кеш зависимостей pip
          # cache-dependency-path можно указать при необходимости (requirements*.txt)

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install isort black flake8

      - name: Lint (scoped)
        run: |
          isort --check-only --profile black \
            tests scripts/train_m7.py scripts/train_octopus_meta.py scripts/calibrate_confidence.py services core/strategy.py
          black --check --line-length 120 \
            tests scripts/train_m7.py scripts/train_octopus_meta.py scripts/calibrate_confidence.py services core/strategy.py
          flake8 \
            tests scripts/train_m7.py scripts/train_octopus_meta.py scripts/calibrate_confidence.py services core/strategy.py

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run tests
        run: pytest -q
