name: Daily Training
on:
  schedule:
    - cron: "30 22 * * 1-5"
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          pip install -r requirements.txt
      - name: ETL
        run: |
          python -m pipelines.etl.daily_etl --tickers "AAPL,MSFT,TSLA" --days 300 --out data/latest.parquet
      - name: Train M7
        run: |
          python -m pipelines.train.train_m7 --data data/latest.parquet --out models/
      - name: Calibrate
        run: |
          python -m pipelines.calib.calibrate_conf --data data/latest.parquet --out config/calibration.json
      - name: Smoke test
        run: |
          python -m pipelines.smoke.smoke_test --tickers "AAPL,MSFT,TSLA"
      - name: Commit models and calib
        run: |
          git config user.name "octo-bot"
          git config user.email "octo-bot@users.noreply.github.com"
          git checkout -b chore/daily-models-${{ github.run_id }}
          git add models/*.joblib models/*.pkl config/calibration.json
          git commit -m "chore: daily models + calibration"
          git push --set-upstream origin chore/daily-models-${{ github.run_id }}
      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/daily-models-${{ github.run_id }}
          title: "Daily models + calibration"
          body: "Auto-updated models and calibration"
