name: ETL

on:
  workflow_dispatch:
    inputs:
      etl_path:
        description: "File path or module (e.g., pipelines/etl/daily_etl.py или pipelines.etl.daily_etl)"
        required: false
        default: ""
      workdir:
        description: "Рабочая директория (если код не в корне)"
        required: false
        default: ""
  schedule:
    - cron: "0 5 * * *"

defaults:
  run:
    shell: bash
    working-directory: ${{ github.event.inputs.workdir || '.' }}

env:
  POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
  ETL_PATH_RAW: ${{ github.event.inputs.etl_path }}
  WORKDIR: ${{ github.event.inputs.workdir || '.' }}

permissions:
  contents: read

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Устанавливаем pyarrow для to_parquet
          pip install pyarrow

      - name: Verify tree
        run: |
          echo "WORKDIR='${WORKDIR}'"
          echo "ETL_PATH_RAW='${ETL_PATH_RAW:-<empty>}'"
          pwd
          ls -R . | head -n 50

      - name: Resolve ETL entrypoint
        id: resolve
        run: |
          set -euo pipefail
          ETL_IN="$(printf '%s' "${ETL_PATH_RAW}" | tr -d '\r' | sed 's/^"//;s/"$//;s/^[[:space:]]*//;s/[[:space:]]*$//')"
          if [ -n "$ETL_IN" ]; then
            if [ -f "$ETL_IN" ]; then
              echo "ETL_FILE=$ETL_IN" >> "$GITHUB_ENV"
              exit 0
            fi
            if [[ "$ETL_IN" =~ ^[A-Za-z0-9_.]+$ && "$ETL_IN" != */* ]]; then
              echo "ETL_MODULE=$ETL_IN" >> "$GITHUB_ENV"
              exit 0
            fi
            echo "Provided etl_path='$ETL_IN' not found in WORKDIR='$WORKDIR'" >&2
            exit 2
          fi
          for c in pipelines/etl/daily_etl.py scripts/etl.py etl.py; do
            [ -f "$c" ] && echo "ETL_FILE=$c" >> "$GITHUB_ENV" && exit 0
          done
          echo "ETL entrypoint not found" >&2
          exit 2

      - name: Run ETL
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          set -euo pipefail
          test -n "${POLYGON_API_KEY:-}" || { echo "POLYGON_API_KEY is not set"; exit 1; }

          # Если модуль — запускаем через -m, это добавляет корень в sys.path
          if [ -n "${ETL_MODULE:-}" ]; then
            python -m "${ETL_MODULE}"
            exit $?
          fi

          # Если файл — пытаемся конвертировать путь в модуль
          if [ -n "${ETL_FILE:-}" ]; then
            MOD="$(echo "$ETL_FILE" | sed 's|^./||;s|/|.|g;s|\.py$||')"
            if python -m "$MOD" --help >/dev/null 2>&1; then
              python -m "$MOD"
              exit $?
            fi
            # Фолбэк: проброс PYTHONPATH на корень проекта
            echo "PYTHONPATH=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"
            PYTHONPATH="$GITHUB_WORKSPACE:$PYTHONPATH" python "$ETL_FILE"
            exit $?
          fi

          echo "No ETL entrypoint resolved"
          exit 2

      # Гарантируем наличие каталога артефактов в рабочей директории
      - name: Prepare artifacts directory
        run: |
          mkdir -p ./artifacts

      # Листинг рабочей директории и ./artifacts перед загрузкой
      - name: List workspace and artifacts
        if: always()
        run: |
          echo "Workspace listing:"
          ls -la
          echo "Artifacts listing (./artifacts):"
          ls -la ./artifacts || true
          echo "Artifacts count:"
          find ./artifacts -mindepth 1 -printf '.' 2>/dev/null | wc -c || true

      # Загрузка артефактов из ./artifacts с жёсткой ошибкой при пустой папке
      - name: Upload ETL artifacts
        uses: actions/upload-artifact@v4
        with:
          name: etl-artifacts-${{ github.run_id }}
          path: ./artifacts/
          if-no-files-found: error
          include-hidden-files: true
          # retention-days: 7  # опционально

