name: ETL

on:
  workflow_dispatch:
    inputs:
      etl_path:
        description: "File path or module (e.g., pipelines/etl/daily_etl.py или pipelines.etl.daily_etl)"
        required: false
        default: ""
      workdir:
        description: "Рабочая директория (если код не в корне)"
        required: false
        default: ""
  schedule:
    - cron: "0 5 * * *"

defaults:
  run:
    shell: bash

env:
  POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
  ETL_PATH_RAW: ${{ github.event.inputs.etl_path }}
  WORKDIR_IN: ${{ github.event.inputs.workdir }}

permissions:
  contents: read

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute paths
        run: |
          set -euo pipefail
          WD="${WORKDIR_IN:-.}"
          # ✅ Исправлено: используем абсолютный путь БЕЗ ./
          ART_DIR="${GITHUB_WORKSPACE}/artifacts"
          echo "WORKDIR_NORM=$WD" >> "$GITHUB_ENV"
          echo "ARTIFACTS_DIR=$ART_DIR" >> "$GITHUB_ENV"
          mkdir -p "$ART_DIR"
          echo "Artifacts dir: $ART_DIR"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyarrow
        working-directory: ${{ env.WORKDIR_NORM }}

      - name: Create required directories
        run: |
          set -euo pipefail
          mkdir -p data logs output models
          echo "Created directories: data, logs, output, models"
        working-directory: ${{ env.WORKDIR_NORM }}

      - name: Verify tree
        run: |
          echo "WORKDIR='${WORKDIR_NORM}'"
          echo "ETL_PATH_RAW='${ETL_PATH_RAW:-<empty>}'"
          pwd
          ls -la | sed -n '1,200p'
        working-directory: ${{ env.WORKDIR_NORM }}

      - name: Resolve ETL entrypoint
        id: resolve
        run: |
          set -euo pipefail
          ETL_IN="$(printf '%s' "${ETL_PATH_RAW:-}" | tr -d '\r' | sed 's/^"//;s/"$//;s/^[[:space:]]*//;s/[[:space:]]*$//')"
          if [ -n "$ETL_IN" ]; then
            if [ -f "$ETL_IN" ]; then
              echo "ETL_FILE=$ETL_IN" >> "$GITHUB_ENV"
              exit 0
            fi
            if [[ "$ETL_IN" =~ ^[A-Za-z0-9_.]+$ && "$ETL_IN" != */* ]]; then
              echo "ETL_MODULE=$ETL_IN" >> "$GITHUB_ENV"
              echo "ETL_FILE_CAND=$(echo "$ETL_IN" | tr '.' '/')".py >> "$GITHUB_ENV"
              exit 0
            fi
            echo "Provided etl_path='$ETL_IN' not found under WORKDIR='${WORKDIR_NORM}'" >&2
            exit 2
          fi
          for c in pipelines/etl/daily_etl.py scripts/etl.py etl.py; do
            [ -f "$c" ] && echo "ETL_FILE=$c" >> "$GITHUB_ENV" && exit 0
          done
          echo "ETL entrypoint not found" >&2
          exit 2
        working-directory: ${{ env.WORKDIR_NORM }}
      
      - name: Run ETL
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          ARTIFACTS_DIR: ${{ env.ARTIFACTS_DIR }}
        run: |
          set -euo pipefail
          test -n "${POLYGON_API_KEY:-}" || { echo "POLYGON_API_KEY is not set"; exit 1; }

          if [ -n "${ETL_MODULE:-}" ]; then
            # try module first
            if python -c "import importlib; importlib.import_module('${ETL_MODULE}')"; then
              python -m "${ETL_MODULE}"
              exit $?
            fi
            # fallback to file path derived from module
            if [ -n "${ETL_FILE_CAND:-}" ] && [ -f "${ETL_FILE_CAND}" ]; then
              echo "Falling back to file: ${ETL_FILE_CAND}"
              PYTHONPATH="$GITHUB_WORKSPACE:${PYTHONPATH:-}" python "${ETL_FILE_CAND}"
              exit $?
            fi
            echo "Module '${ETL_MODULE}' not importable and no file fallback" >&2
            exit 1
          fi

          if [ -n "${ETL_FILE:-}" ]; then
            MOD="$(echo "$ETL_FILE" | sed 's|^./||;s|/|.|g;s|\.py$||')"
            if python -m "$MOD" --help >/dev/null 2>&1; then
              python -m "$MOD"
              exit $?
            fi
            PYTHONPATH="$GITHUB_WORKSPACE:${PYTHONPATH:-}" python "$ETL_FILE"
            exit $?
          fi

          echo "No ETL entrypoint resolved"
          exit 2
        working-directory: ${{ env.WORKDIR_NORM }}

      - name: Collect logs
        if: always()
        run: |
          set -euo pipefail
          for d in logs output data; do
            [ -d "$d" ] && rsync -a "$d"/ "${ARTIFACTS_DIR}/$d"/ || true
          done
        working-directory: ${{ env.WORKDIR_NORM }}
      
      - name: List workspace and artifacts
        if: always()
        run: |
          echo "Workspace listing:" && ls -la "${GITHUB_WORKSPACE}/${WORKDIR_NORM#/}" || true
          echo "Artifacts listing (${ARTIFACTS_DIR}):" && ls -la "${ARTIFACTS_DIR}" || true

      - name: Upload ETL artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: etl-artifacts-${{ github.run_id }}
          path: ${{ env.ARTIFACTS_DIR }}
          if-no-files-found: warn
          retention-days: 7
