# .github/workflows/etl.yml
name: ETL
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  etl:
    runs-on: ubuntu-latest
    env:
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run ETL
        run: |
          test -n "${POLYGON_API_KEY:-}" || { echo "POLYGON_API_KEY is not set"; exit 1; }
          python scripts/etl.py
