[theme]
base="dark"
primaryColor="#271382"
backgroundColor="#000000"
secondaryBackgroundColor="#55555a"
[client]
toolbarMode = "minimal"   # скрывает «три точки» и верхнюю панель
[browser]
gatherUsageStats = false
