POLYGON_API_KEY = "ooSjpJAULw4VXxsY28ck7DQST7i13kcG"
ARXORA_MODEL_DIR = "models"
ARXORA_AI_TH_LONG = 0.70
ARXORA_AI_TH_SHORT = 0.70
ARXORA_AI_PSEUDO = 0
ARXORA_SHOW_TRAINERS = 0        # 0 = скрыть, 1 = показывать всегда
ARXORA_TRAINER_PASS   = "admin"  # любой PIN, чтобы открывать панели
